import { NextResponse } from "next/server";
import { getCaseDefinition } from "@cases/registry";
import {
  ensureCaseObject,
  ensureCaseSeeded,
  getCaseStore,
} from "@cases/runtime.server";
import { authorizeCommandActor } from "@cases/command-authorization";
import { validateDomainCommand } from "@cases/domain-command";

type CommandBody = {
  command?: string;
  actorRole?: string;
  actorId?: string;
  expectedVersion?: number;
  idempotencyKey?: string;
  reason?: string;
  evidenceIds?: string[];
  data?: Record<string, unknown>;
};

const errorStatus: Record<string, number> = {
  version_conflict: 409,
  role_forbidden: 403,
  transition_forbidden: 422,
  command_unknown: 400,
  object_not_found: 404,
  actor_invalid: 400,
  evidence_invalid: 400,
  task_payload_too_large: 413,
  task_input_required: 422,
  candidate_required: 422,
  candidate_invalid: 422,
  return_object_required: 422,
  return_evidence_invalid: 422,
  return_evidence_mismatch: 422,
  evidence_request_required: 422,
  evidence_incomplete: 422,
  assignee_required: 422,
  due_at_required: 422,
  review_note_required: 422,
  decision_reason_required: 422,
  event_required: 422,
  authoritative_state_required: 422,
  reconciliation_reason_required: 422,
  sender_actor_required: 422,
  receiver_actor_required: 422,
  actor_separation_required: 422,
  cosign_note_required: 422,
  late_event_required: 422,
  hospital_object_required: 422,
  hospital_event_invalid: 422,
  hospital_evidence_mismatch: 422,
  hospital_state_invalid: 422,
  segment_required: 422,
  investigation_reason_required: 422,
  segment_mismatch: 422,
  boiler_object_required: 422,
  boiler_task_required: 422,
  boiler_object_mismatch: 422,
  boiler_evidence_mismatch: 422,
  boiler_condition_invalid: 422,
  boiler_confirmation_invalid: 422,
  business_idempotency_key_required: 422,
  local_recovery_key_required: 422,
  telecom_lookup_target_required: 422,
  telecom_lookup_result_invalid: 422,
  telecom_lookup_summary_required: 422,
  telecom_lookup_evidence_required: 422,
  telecom_lookup_evidence_mismatch: 422,
  idempotency_key_mismatch: 422,
  idempotency_conflict: 409,
  trial_plan_required: 422,
  trial_hypothesis_required: 422,
  trial_cohort_required: 422,
  trial_cohort_invalid: 422,
  trial_seed_required: 422,
  trial_assignment_required: 422,
  trial_assignment_overlap: 422,
  trial_assignment_invalid: 422,
  trial_assignment_ratio_invalid: 422,
  trial_measurement_required: 422,
  trial_budget_required: 422,
  trial_budget_invalid: 422,
  trial_stop_rule_required: 422,
  trial_stop_rule_invalid: 422,
  persisted_task_required: 422,
  review_task_required: 422,
  review_aspect_required: 422,
  review_aspect_invalid: 422,
  review_evidence_required: 422,
  review_evidence_invalid: 422,
  review_evidence_overlap: 422,
  review_question_required: 422,
  review_method_required: 422,
  review_sample_required: 422,
  review_sample_invalid: 422,
  due_at_invalid: 422,
  review_window_required: 422,
  review_success_criteria_required: 422,
  review_task_mismatch: 422,
  credit_material_required: 422,
  credit_material_invalid: 422,
  credit_application_required: 422,
  credit_request_note_required: 422,
  credit_material_incomplete: 422,
  credit_evidence_mismatch: 422,
  air_release_object_required: 422,
  air_release_package_required: 422,
  air_release_package_mismatch: 422,
  air_release_completeness_mismatch: 422,
  air_release_incomplete: 422,
  air_release_evidence_mismatch: 422,
  air_release_missing_required: 422,
  architecture_facts_required: 422,
  architecture_facts_invalid: 422,
  architecture_hypothesis_required: 422,
  architecture_constraints_required: 422,
  architecture_constraints_invalid: 422,
  architecture_risks_required: 422,
  architecture_risks_invalid: 422,
  architecture_object_required: 422,
  architecture_adr_required: 422,
  architecture_adr_invalid: 422,
  architecture_evidence_mismatch: 422,
  architecture_rationale_required: 422,
  architecture_signature_required: 422,
  architecture_signature_invalid: 422,
  architecture_contract_required: 422,
  architecture_contract_invalid: 422,
  observability_evidence_required: 422,
  observability_evidence_invalid: 422,
  handoff_object_mismatch: 422,
  safety_check_incomplete: 422,
  technician_required: 422,
  response_window_required: 422,
  handoff_note_required: 422,
  details_request_required: 422,
  actor_mismatch: 422,
  process_review_required: 422,
  process_window_required: 422,
  process_window_invalid: 422,
  process_object_mismatch: 422,
  process_hypothesis_required: 422,
  process_hypothesis_invalid: 422,
  process_evidence_required: 422,
  process_evidence_invalid: 422,
  process_task_mismatch: 422,
  field_event_mismatch: 422,
  field_evidence_issue_required: 422,
  field_evidence_issue_mismatch: 422,
  field_evidence_required: 422,
  field_operator_required: 422,
  field_capture_required: 422,
  field_photo_required: 422,
  field_reading_required: 422,
  field_reading_invalid: 422,
  field_issue_unresolved: 422,
  telemetry_window_incomplete: 422,
  telemetry_gap_unresolved: 422,
  retrieval_question_required: 422,
  retrieval_query_required: 422,
  retrieval_trace_required: 422,
  retrieval_query_mismatch: 422,
  retrieval_window_required: 422,
  retrieval_window_invalid: 422,
  retrieval_results_required: 422,
  retrieval_results_invalid: 422,
  retrieval_evidence_mismatch: 422,
  retrieval_task_mismatch: 422,
  retrieval_citation_required: 422,
  retrieval_citation_overlap: 422,
  retrieval_citation_invalid: 422,
  inspection_checklist_required: 422,
  inspection_action_invalid: 422,
  model_candidate_required: 422,
  model_candidate_mismatch: 422,
  model_policy_required: 422,
  model_policy_mismatch: 422,
  model_evaluation_required: 422,
  model_evaluation_mismatch: 422,
  model_gate_set_required: 422,
  model_gate_set_invalid: 422,
  model_retest_required: 422,
  model_retest_mismatch: 422,
  model_retest_sample_invalid: 422,
  model_retest_invalid: 422,
  model_decision_invalid: 422,
  model_comparator_invalid: 422,
  model_retest_not_passed: 422,
  model_review_required: 422,
  model_gate_not_passed: 422,
  cold_chain_window_required: 422,
  cold_chain_window_invalid: 422,
  cold_chain_investigation_required: 422,
  cold_chain_investigation_mismatch: 422,
  cold_chain_events_required: 422,
  cold_chain_events_invalid: 422,
  cold_chain_observation_required: 422,
  cold_chain_peak_mismatch: 422,
  cold_chain_excursion_mismatch: 422,
  cold_chain_decision_invalid: 422,
  cold_chain_evidence_required: 422,
  cold_chain_evidence_unverified: 422,
  cold_chain_evidence_mismatch: 422,
  cold_chain_freeze_scope_invalid: 422,
  wafer_retest_required: 422,
  wafer_object_required: 422,
  wafer_version_required: 422,
  wafer_object_mismatch: 422,
  wafer_sensor_required: 422,
  wafer_sensor_invalid: 422,
  wafer_sensor_mismatch: 422,
  wafer_evidence_mismatch: 422,
  wafer_retest_task_required: 422,
  wafer_retest_task_invalid: 422,
  wafer_retest_task_mismatch: 422,
  wafer_requester_required: 422,
  wafer_checklist_required: 422,
  wafer_supervisor_review_invalid: 422,
  wind_investigation_required: 422,
  wind_object_required: 422,
  wind_version_required: 422,
  wind_object_mismatch: 422,
  wind_window_required: 422,
  wind_window_mismatch: 422,
  wind_request_required: 422,
  wind_request_invalid: 422,
  wind_request_mismatch: 422,
  wind_checklist_required: 422,
  wind_checklist_invalid: 422,
  wind_evidence_required: 422,
  wind_evidence_invalid: 422,
  wind_evidence_mismatch: 422,
  wind_inspector_required: 422,
  wind_inspection_required: 422,
  wind_inspection_invalid: 422,
  wind_confirmation_invalid: 422,
  cutter_review_required: 422,
  cutter_object_required: 422,
  cutter_version_required: 422,
  cutter_object_mismatch: 422,
  cutter_source_required: 422,
  cutter_source_mismatch: 422,
  cutter_waveform_required: 422,
  cutter_channel_required: 422,
  cutter_channel_invalid: 422,
  cutter_evidence_mismatch: 422,
  cutter_plan_required: 422,
  cutter_plan_invalid: 422,
  cutter_plan_mismatch: 422,
  cutter_signal_required: 422,
  cutter_cursor_required: 422,
  cutter_cursor_invalid: 422,
  cutter_cursor_mismatch: 422,
  cutter_window_required: 422,
  cutter_window_invalid: 422,
  cutter_direction_required: 422,
  cutter_confirmation_invalid: 422,
  cutter_sample_count_required: 422,
  cutter_continuation_invalid: 422,
  hydraulic_object_required: 422,
  hydraulic_task_required: 422,
  hydraulic_object_mismatch: 422,
  hydraulic_task_mismatch: 422,
  hydraulic_order_required: 422,
  hydraulic_order_invalid: 422,
  hydraulic_order_mismatch: 422,
  hydraulic_order_unconfirmed: 422,
  hydraulic_review_required: 422,
  hydraulic_review_invalid: 422,
  hydraulic_review_incomplete: 422,
  hydraulic_basis_required: 422,
  hydraulic_basis_invalid: 422,
  hydraulic_evidence_mismatch: 422,
  hydraulic_confirmation_invalid: 422,
  pv_object_required: 422,
  pv_task_required: 422,
  pv_object_mismatch: 422,
  pv_task_mismatch: 422,
  pv_direction_required: 422,
  pv_direction_invalid: 422,
  pv_direction_mismatch: 422,
  pv_sources_required: 422,
  pv_sources_invalid: 422,
  pv_retrieval_required: 422,
  pv_retrieval_invalid: 422,
  pv_evidence_mismatch: 422,
  pv_confirmation_invalid: 422,
  pv_control_block_invalid: 422,
};

export async function POST(
  request: Request,
  context: { params: Promise<{ caseId: string; objectId: string }> },
) {
  const { caseId, objectId } = await context.params;
  const definition = getCaseDefinition(caseId);
  if (!definition) {
    return NextResponse.json({ error: "case_not_found" }, { status: 404 });
  }
  const dataset = ensureCaseSeeded(definition);
  try {
    ensureCaseObject(definition, objectId);
  } catch (error) {
    const message = error instanceof Error ? error.message : "object_not_found";
    return NextResponse.json(
      { error: message },
      { status: message === "object_not_found" ? 404 : 500 },
    );
  }
  const body = (await request.json()) as CommandBody;
  if (
    !body.command ||
    !body.actorRole ||
    typeof body.expectedVersion !== "number" ||
    !body.idempotencyKey ||
    (body.data !== undefined &&
      (typeof body.data !== "object" || body.data === null || Array.isArray(body.data))) ||
    (body.evidenceIds !== undefined &&
      (!Array.isArray(body.evidenceIds) ||
        body.evidenceIds.some((item) => typeof item !== "string")))
  ) {
    return NextResponse.json({ error: "invalid_command" }, { status: 400 });
  }
  const authorizationError = authorizeCommandActor(
    definition,
    body.command,
    body.actorRole,
  );
  if (authorizationError) {
    return NextResponse.json(
      { error: authorizationError },
      { status: errorStatus[authorizationError] },
    );
  }
  try {
    const store = getCaseStore(definition);
    const evidenceIds = body.evidenceIds ?? ["dataset-row"];
    validateDomainCommand({
      caseId: definition.id,
      command: body.command,
      actorRole: body.actorRole,
      actorId: body.actorId,
      idempotencyKey: body.idempotencyKey,
      reason: body.reason,
      evidenceIds,
      data: body.data,
      current: store.project(definition.id, objectId),
      sceneRows: dataset.sceneRows,
      supportingArtifacts: dataset.supportingArtifacts,
    });
    const result = store.dispatch({
      caseId: definition.id,
      objectId,
      command: body.command,
      actor: {
        id: body.actorId?.trim() || `local-${body.actorRole}`,
        role: body.actorRole,
      },
      expectedVersion: body.expectedVersion,
      idempotencyKey: body.idempotencyKey,
      reason: body.reason,
      evidenceIds,
      data: body.data,
    });
    return NextResponse.json(result);
  } catch (error) {
    const message = error instanceof Error ? error.message : "command_failed";
    return NextResponse.json(
      { error: message },
      { status: errorStatus[message] ?? 500 },
    );
  }
}
